In [1]:
!pip install torch

In [3]:
!pip install torchvision torchtext

   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ------------------------------------- -- 1.8/2.0 MB 14.4 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 12.0 MB/s eta 0:00:00


In [2]:
import torch

In [61]:
w=torch.tensor(1.0,requires_grad=True)
w**2

tensor(1., grad_fn=<PowBackward0>)

In [62]:
x=3
z=w*x
out=z**2
out.backward()
print(f'out -> w로 미분 : {w.grad}',w.grad)

out -> w로 미분 : 18.0 tensor(18.)


# 텐서


In [70]:
import numpy as np
import torch

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.size(),x.shape,x.ndimension()

(torch.Size([3, 3]), torch.Size([3, 3]), 2)

In [75]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x=torch.unsqueeze(x,1)
x,x.shape

(tensor([[[1, 2, 3]],
 
         [[4, 5, 6]],
 
         [[7, 8, 9]]]),
 torch.Size([3, 1, 3]))

In [76]:
x=torch.squeeze(x)
x.shape

torch.Size([3, 3])

In [80]:
x.view(-1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x+np.array([1,1,1])

C:\Users\ksa\AppData\Local\Temp\ipykernel_7608\2819094879.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  x+np.array([1,1,1])


tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [82]:
np.array([1,1,1]).shape

(3,)

In [106]:
# 행,렬 -> 고차원,저차원
w=torch.randn(5,3,dtype=torch.float)
x=torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
w.shape,x.shape

(torch.Size([5, 3]), torch.Size([3, 2]))

In [104]:
w.shape

torch.Size([5, 3])

ex1) w * x = (5,3) * (3,)


ex2) x * w = (,5) * (5,3)

In [105]:
w,w.T

(tensor([[ 1.6116, -0.4846,  1.5859],
         [ 2.7442, -0.7146,  0.9676],
         [-0.7375,  1.5618,  0.2230],
         [ 0.8914,  0.4112, -0.1946],
         [ 0.4800,  0.8033, -0.7898]]),
 tensor([[ 1.6116,  2.7442, -0.7375,  0.8914,  0.4800],
         [-0.4846, -0.7146,  1.5618,  0.4112,  0.8033],
         [ 1.5859,  0.9676,  0.2230, -0.1946, -0.7898]]))

In [109]:
b=torch.randn(5,2,dtype=torch.float)
b.shape

torch.Size([5, 2])

In [115]:
wx=torch.mm(w,x)
torch.mm(w,x).shape

torch.Size([5, 2])

In [116]:
z=wx+b
z

tensor([[ 1.0080,  0.1469],
        [ 0.2420, -2.1159],
        [ 2.9640,  4.9390],
        [ 1.2673, -0.1661],
        [ 1.2762,  2.6294]])

In [118]:
import numpy as np
import torch
from sklearn.datasets import make_blobs

n_dim=2
tr_x,tr_y=make_blobs(n_samples=80,n_features=2,centers=[[1,1],[-1,-1],[1,-1],[-1,1]],shuffle=True,cluster_std=0.3)
tt_x,tt_y=make_blobs(n_samples=80,n_features=2,centers=[[1,1],[-1,-1],[1,-1],[-1,1]],shuffle=True,cluster_std=0.3)

In [ ]:
def label_map(y,from_,n):
    ck_y=y.copy()
    for i in [0,1]:
        ck_y[y==i]=n
    return ck_y

tr_y=label_map(tr_y,[0,1],0)
tr_y=label_map(tr_y,[2,3],1)
tt_y=label_map(tr_y,[0,1],0)
tt_y=label_map(tr_y,[2,3],0)

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0])